spring:
  application:
    name: admin-console
  boot:
    admin:
      client:
        instance:
          metadata:
            tags:
              environment: dev
  # 视图配置
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    template-loader-path: classpath:/templates/

  mvc:
    favicon:
      enabled: false
# 服务端口配置
server:
  port: 8050
# 日志配置
logging:
  path: /logs
  file: ${logging.path}/${spring.application.name}-${server.port}.log
  level:
    root: info
    com.lx.framework.utils: debug
    com.xpay.merchant.client: debug

# 配置文件读取配置
config:
  dir: E:\GitLab-Dev\XPay\config\${spring.application.name}

# 服务注册中心和发现配置
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:10020/eureka

# 设置使用 Feign 调用服务的连接和超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 15000

ribbon:
  ReadTimeout: 5000
  ConnectionTimeout: 500

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  tags:
    environment: dev
